<a href="https://colab.research.google.com/github/akmhel/Team-Go/blob/master/Recommdatxn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [141]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [0]:
import pandas as pd
import numpy as np
import pandas_profiling
import seaborn as sb
import matplotlib.pyplot as plt
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import linear_kernel
tfidf = TfidfVectorizer(stop_words='english')

In [143]:
post_data = pd.read_csv('/content/drive/My Drive/Colab Notebooks/posts.csv')
post_data2 = post_data.copy()
post_data2.head()

   id  user_id                              title  ... status_id action post_id
0   1     2077  What i have learnt so far on HTML  ...       NaN    NaN     NaN
1   2     1719                   HTML BEGINS HERE  ...       NaN    NaN     NaN
2   4     1310            My Laziness In The Open  ...       NaN    NaN     NaN
3   6     1787                          MY TASK 2  ...       NaN    NaN     NaN
4   7      167                             Task 2  ...       NaN    NaN     NaN

[5 rows x 12 columns]

In [144]:
post_data2.dtypes

id              int64
user_id         int64
title          object
content        object
tags           object
slug           object
created_at     object
updated_at     object
image          object
status_id     float64
action         object
post_id       float64
dtype: object

In [145]:
user_data = pd.read_csv('/content/drive/My Drive/Colab Notebooks/users.csv')
user_data2 = user_data.copy()
user_data2.head()

   user_id  ...                                          short_bio
0        1  ...               Software Developer | DevOPs Engineer
1        2  ...                                      Web Developer
2        3  ...  Front End Developer | React Developer | Mentor...
3        4  ...  | Software Developer | DevOps Engineer | @linu...
4        5  ...            I Am lamar and you don't think am real?

[5 rows x 12 columns]

In [146]:
user_data2.dtypes

user_id             int64
name               object
username           object
email              object
image              object
provider           object
provider_id       float64
password          float64
remember_token     object
created_at         object
updated_at         object
short_bio          object
dtype: object

In [0]:
df = pd.merge(post_data2, user_data2, on='user_id')

In [148]:
metadata = df.copy()
df.head()

   id  ...                                          short_bio
0   1  ...  I am a person of Growth mindset. I believe i c...
1   2  ...  I am Kolawole Adebayo Ogunfowokan, I am a trai...
2   4  ...                               Front-End enthusiast
3   6  ...                                                NaN
4  11  ...                                                NaN

[5 rows x 23 columns]

**Keeps Only Column We'll need**

In [149]:
keep_cols = ['id', 'user_id', 'title', 'content', 'name', 'username']
metadata = metadata[keep_cols]

# Drop row with null title
null_title = metadata[metadata['title'].isna()].index
metadata.drop(index = null_title, inplace = True)

metadata.reset_index(drop = True, inplace = True)

print(metadata.shape)
metadata.head()

(876, 6)

   id  user_id  ...                name          username
0   1     2077  ...        jason obiako        obiako4u53
1   2     1719  ...       Kolawole John      kolawolejohn
2   4     1310  ...  Oladele Makanjuola           Oladele
3   6     1787  ...      Emmanuel ulaka  emmanuel.ulaka16
4  11     1787  ...      Emmanuel ulaka  emmanuel.ulaka16

[5 rows x 6 columns]

In [150]:
metadata.shape

(876, 6)

In [151]:
metadata.describe()

                id      user_id
count   876.000000   876.000000
mean    516.808219  1061.639269
std     278.648058   788.070779
min       1.000000     1.000000
25%     278.750000   338.000000
50%     523.500000   944.000000
75%     754.250000  1836.250000
max    1007.000000  2297.000000

In [152]:
metadata.isnull().sum()

id          0
user_id     0
title       0
content     0
name        0
username    0
dtype: int64

In [0]:
metadata.dropna(axis=1, inplace=True)

In [154]:
metadata.isnull().sum

<bound method DataFrame.sum of         id  user_id  title  content   name  username
0    False    False  False    False  False     False
1    False    False  False    False  False     False
2    False    False  False    False  False     False
3    False    False  False    False  False     False
4    False    False  False    False  False     False
5    False    False  False    False  False     False
6    False    False  False    False  False     False
7    False    False  False    False  False     False
8    False    False  False    False  False     False
9    False    False  False    False  False     False
10   False    False  False    False  False     False
11   False    False  False    False  False     False
12   False    False  False    False  False     False
13   False    False  False    False  False     False
14   False    False  False    False  False     False
15   False    False  False    False  False     False
16   False    False  False    False  False     False
17   False    False  False    False  False     False
18   False    False  False    False  False     False
19   False    False  False    False  False     False
20   False    False  False    False  False     False
21   False    False  False    False  False     False
22   False    False  False    False  False     False
23   False    False  False    False  False     False
24   False    False  False    False  False     False
25   False    False  False    False  False     False
26   False    False  False    False  False     False
27   False    False  False    False  False     False
28   False    False  False    False  False     False
29   False    False  False    False  False     False
..     ...      ...    ...      ...    ...       ...
846  False    False  False    False  False     False
847  False    False  False    False  False     False
848  False    False  False    False  False     False
849  False    False  False    False  False     False
850  False    False  False    False  False     False
851  False    False  False    False  False     False
852  False    False  False    False  False     False
853  False    False  False    False  False     False
854  False    False  False    False  False     False
855  False    False  False    False  False     False
856  False    False  False    False  False     False
857  False    False  False    False  False     False
858  False    False  False    False  False     False
859  False    False  False    False  False     False
860  False    False  False    False  False     False
861  False    False  False    False  False     False
862  False    False  False    False  False     False
863  False    False  False    False  False     False
864  False    False  False    False  False     False
865  False    False  False    False  False     False
866  False    False  False    False  False     False
867  False    False  False    False  False     False
868  False    False  False    False  False     False
869  False    False  False    False  False     False
870  False    False  False    False  False     False
871  False    False  False    False  False     False
872  False    False  False    False  False     False
873  False    False  False    False  False     False
874  False    False  False    False  False     False
875  False    False  False    False  False     False

[876 rows x 6 columns]>

In [155]:
metadata.describe()

                id      user_id
count   876.000000   876.000000
mean    516.808219  1061.639269
std     278.648058   788.070779
min       1.000000     1.000000
25%     278.750000   338.000000
50%     523.500000   944.000000
75%     754.250000  1836.250000
max    1007.000000  2297.000000

In [156]:
pandas_profiling.ProfileReport(metadata)

In [157]:
metadata.corr(method = 'pearson')

               id   user_id
id       1.000000 -0.165137
user_id -0.165137  1.000000

In [158]:
metadata.corr(method = 'kendall')

               id   user_id
id       1.000000 -0.104611
user_id -0.104611  1.000000

In [159]:
metadata.columns

Index(['id', 'user_id', 'title', 'content', 'name', 'username'], dtype='object')

In [0]:
tfidf_matrix = tfidf.fit_transform(metadata['content'])

In [162]:
tfidf_matrix.shape

(876, 5122)

In [0]:
cosine_sim = linear_kernel(tfidf_matrix, tfidf_matrix)

In [0]:
indices = pd.Series(metadata.index, index=metadata['title']).drop_duplicates()

In [0]:
def get_recommendations(title, cosine_sim=cosine_sim):
  idx = indices[title]
  sim_scores = list(enumerate(cosine_sim[idx]))
  sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
  sim_scores = sim_scores[1:11]
  movie_indices = [i[0] for i in sim_scores]
  return metadata['title'].iloc[movie_indices]

In [165]:
get_recommendations('What i have learnt so far on HTML')

265                              third
308            WHAT I'VE LEARNT SO FAR
775                             TASK 2
776                             TASK 2
141                      CV Using html
261                               TEst
237           Startng task 2 Completed
28     WHAT I HAVE DONE SO FAR ON HTML
16                  What I done so far
51        Lucid post to start.ng Task1
Name: title, dtype: object

In [166]:
get_recommendations('Welcome to Lucid')

571                    pre- intership on startng
590                                        ochem
464                      my 2nd task on start.ng
465                      my 2nd task on start.ng
615                                My First Post
582                               Test an image.
449         Converting Cv to Html StartNg Task 2
502                      Journey round the world
504                               Journey so far
574    THE SKY IS MY STEPPING STONE WITH STARTNG
Name: title, dtype: object

In [168]:
metadata.title

0                      What i have learnt so far on HTML
1                                       HTML BEGINS HERE
2                                My Laziness In The Open
3                                              MY TASK 2
4                                              MY TASK 2
5                                                 Task 2
6                                Daily Log - CLASS DAY 1
7                                     My Journey on HTML
8                                            Please note
9                                     My Journey on HTML
10                                    My learning so far
11                               StartNG HTML Exposition
12                                     StartNG HTML task
13                             On StartNG Pre-Internship
14                                                   why
15                         HNG internship journey so far
16                                    What I done so far
17                             Learnt Learn and Learning
18                      How far we can go with just HTML
19                   Learning Web development at StartNg
20     The Journey with StartNG: Creating my CV with ...
21     The Journey with StartNG: Creating my CV with ...
22                                    The Journey So Far
23                                    The Journey So Far
24                                    The Journey So Far
25                   What i have done so far on start.ng
26                                         Task Number 7
27                          What has been learnt so far?
28                       WHAT I HAVE DONE SO FAR ON HTML
29                                                TASK 2
                             ...
846                           software testing for lucid
847                                      My html project
848                                      My html project
849                                    My Start.ng story
850    Overcoming the Rough Road to Front End Develop...
851    We Finally Have a Carbon-dioxide-filled Market...
852     How Not to Miss Important Information on StartNG
853                  User Acceptance Testing Using Lucid
854                                 HNGInternship6 Rules
855                                        StartNG Class
856                                   MY HTML EXPERIENCE
857                           ELLA'S START-NG EXPERIENCE
858                                           Post title
859                                            html test
860                  YOUR HIGH IQ WILL KILL YOUR STARTUP
861    A CHINESE VILLAGER WHO SELLS MORE SOFTWARE DAI...
862                BUILD AROUND YOUR DISCOVERY MECHANISM
863                      DON'T ASK WHY YOU WERE REJECTED
864                                        THE SUNFLOWER
865                                     Welcome to Lucid
866                                        This is lucid
867                                  this is a test post
868                                         this is mine
869                                 Your face PHP script
870                                         with picture
871                                 Post with two images
872                                                 asda
873                                       Speed Of Light
874                                                Am ok
875                                            jbhjkhkbb
Name: title, Length: 876, dtype: object